version: 2.1
jobs:
  deploy_image:
    working_directory: ~/app
    docker:
      - image: circleci/arm64v8/alpine:3.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build the app docker image
          command: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
            docker build --tag tttmaximttt/gobot:$CIRCLE_BRANCH .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push tttmaximttt/gobot:$CIRCLE_BRANCH


workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy_image:
          context: DOCKER_HUB
          filters:
            branches:
              only: master