orbs:
  farm: f0cal/farm@1.0.0
version: 2.1
jobs:
  deploy_image:
    working_directory: ~/repo
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build the app docker image
          command: |
            TAG=0.0.$CIRCLE_BUILD_NUM
            docker build --tag tttmaximttt/gobot:TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push tttmaximttt/gobot:$TAG


workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy_image:
          context: DOCKER_HUB
          filters:
            branches:
              only: master